SOCIAL_AUTH_TWITTER_KEY = 'rFGT3DYe8cpfD0B6BguZ8ilHh'
SOCIAL_AUTH_TWITTER_SECRET = 'vZXN95NRIFaR9W3o4ES3qQUvH907JvKucvR5FAB7yoFjQfUF2q'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
