# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycritic_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauth_secret',
            field=models.CharField(default='nothing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauth_token',
            field=models.CharField(default='nothing', max_length=200),
            preserve_default=False,
        ),
    ]
