# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycritic_app', '0007_auto_20170502_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='identifier',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
