# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycritic_app', '0009_auto_20170502_0711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user_id', 'movie_id')]),
        ),
    ]
