# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycritic_app', '0011_auto_20170502_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_scores',
            field=models.TextField(blank=True),
        ),
    ]
