# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycritic_app', '0012_auto_20170502_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_scores',
            new_name='similarity_scores',
        ),
    ]
