# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycritic_app', '0013_auto_20170502_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_list',
            field=models.TextField(default='[]'),
        ),
    ]
